### PR TITLE
Added parse-number

### PR DESCRIPTION
**Pull request by eliascotto**
Issue #2

### CODE REVIEW

**Comment by borkdude** [comment]
Hey! I think this can be easier implemented as `#(Long/parseLong %)` ?

**Comment by borkdude** [comment]
Which version of babashka are you using btw? Or using it in Clojure?

**Comment by eliascotto** [comment]
I'm using `0.5.1`. Yes, `parseLong` would be better

**Comment by borkdude** [comment]
I recommend upgrading to 0.7.8. `parse-long` is a new function in Clojure 1.11 which is now in bb.

**Pull request merged**
